<Project Sdk="Godot.NET.Sdk/4.5.1">
  <!-- 导入本地配置文件 -->
  <Import Project="Local.props" Condition="Exists('Local.props')" />

  <PropertyGroup>
    <!-- 修改 .NET 运行时的版本 -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- 如果 Local.props 未设置路径，报错 -->
    <Sts2Dir Condition="'$(Sts2Dir)' == ''">ERROR_MISSING_STS2_DIR</Sts2Dir>
    <Sts2DataDir>$(Sts2Dir)\data_sts2_windows_x86_64</Sts2DataDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2DataDir)\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>$(Sts2DataDir)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- NuGet获取，备用 -->
    <!-- <PackageReference Include="STS2.RitsuLib" Version="*" /> -->

    <!-- 本地引用 Local.props -->
    <Reference Include="STS2-RitsuLib">
      <RitsuLibDllPath Condition="'$(RitsuLibDllPath)' == ''">ERROR_MISSING_RITSU</RitsuLibDllPath>
      <HintPath>$(RitsuLibDllPath)</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ElfredaSpire\scripts\Characters\Crusader\Potions\" />
    <Folder Include="ElfredaSpire\scripts\Characters\HighwayMan\Events\" />
    <Folder Include="ElfredaSpire\scripts\Characters\HighwayMan\Potions\" />
  </ItemGroup>

  <!-- 自动复制dll和json -->
  <Target Name="Copy Mod" AfterTargets="PostBuildEvent">
    <Message Text="Copying mod to Slay the Spire 2 mods folder..." Importance="high" />
    <MakeDir Directories="$(Sts2Dir)\mods\" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Dir)\mods\$(MSBuildProjectName)\" />
    <Copy SourceFiles="$(MSBuildProjectName).json" DestinationFolder="$(Sts2Dir)/mods/$(MSBuildProjectName)/" />
  </Target>

  <Target Name="ExportPckRider" AfterTargets="Publish">
      <Message Text="Copying PCK to Slay the Spire 2 mods folder..." Importance="high" />
      <Exec Command="&quot;$(GodotEXEPath)&quot; --headless --export-pack &quot;Windows Desktop&quot; &quot;$(Sts2Dir)/mods/$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
            EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"
            ContinueOnError="WarnAndContinue" />
  </Target>

  <Target Name="Pack">
    <Message Text="Copying PCK to Slay the Spire 2 mods folder..." Importance="high" />
    <Exec Command="&quot;$(GodotEXEPath)&quot; --headless --export-pack &quot;Windows Desktop&quot; &quot;$(Sts2Dir)/mods/$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
      EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"
      ContinueOnError="WarnAndContinue" />
  </Target>
</Project>